# frozen_string_literal: true

require_relative "base_serializer"
require_relative "fix_vec_serializer"
require_relative "dyn_vec_serializer"
require_relative "struct_serializer"
require_relative "table_serializer"
require_relative "uint32_serializer"
require_relative "uint64_serializer"
require_relative "byte32_serializer"
require_relative "byte_serializer"
require_relative "code_hash_serializer"
require_relative "hash_type_serializer"
require_relative "bytes_serializer"
require_relative "script_serializer"
require_relative "version_serializer"
require_relative "header_dep_serializer"
require_relative "dep_type_serializer"
require_relative "cell_dep_serializer"
require_relative "since_serializer"
require_relative "input_serializer"
require_relative "capacity_serializer"
require_relative "output_serializer"
require_relative "out_point_tx_hash_serializer"
require_relative "out_point_index_serializer"
require_relative "out_point_serializer"
require_relative "output_data_serializer"
require_relative "raw_transaction_serializer"
require_relative "witness_serializer"
require_relative "transaction_serializer"
require_relative "bytes_opt_serializer"
require_relative "witness_args_serializer"
require_relative "block_serializer"
require_relative "header_serializer"
require_relative "proposal_short_id_serializer"
require_relative "raw_header_serializer"
require_relative "uint128_serializer"
require_relative "uncle_block_serializer"

module CKB
  module Serializers
  end
end
